In [1]:
import numpy as np
np.random.seed(21)
arr = np.random.uniform(50, 150, 8)
print("Raw Array:")
print(arr)
rounded_arr = np.round(arr, 2)
print("\nRounded Array:")
print(rounded_arr)
zeros = np.zeros((2, 4))
print("\n2 x 4 Array of Zeros:")
print(zeros)
ones = np.ones((2, 4))
print("\n2 x 4 Array of Ones:")
print(ones)
reshaped_arr = rounded_arr.reshape(2, 4)
print("\nReshaped 2 x 4 Array:")
print(reshaped_arr)
result = reshaped_arr + 10
print("\nArray after adding 10:")
print(result)

Raw Array:
[ 54.87248808  78.91096598 122.09663468  52.16162499  70.59227653
  55.07732567  80.2271894  116.39102946]

Rounded Array:
[ 54.87  78.91 122.1   52.16  70.59  55.08  80.23 116.39]

2 x 4 Array of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2 x 4 Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Reshaped 2 x 4 Array:
[[ 54.87  78.91 122.1   52.16]
 [ 70.59  55.08  80.23 116.39]]

Array after adding 10:
[[ 64.87  88.91 132.1   62.16]
 [ 80.59  65.08  90.23 126.39]]
