In [1]:
import numpy as np
np.random.seed(42)
arr = np.random.randint(10, 100, size=(6, 6))
print("6 x 6 Array:")
print(arr)
row_sum = np.sum(arr, axis=1)
print("\nSum of each row:")
print(row_sum)
column_sum = np.sum(arr, axis=0)
print("\nSum of each column:")
print(column_sum)
row_mean = np.round(np.mean(arr, axis=1), 2)
print("\nMean of each row:")
print(row_mean)
row_max = np.max(arr, axis=1)
print("\nMaximum value in each row:")
print(row_max)
max_index = np.argmax(arr, axis=1)
print("\nColumn index of maximum value in each row:")
print(max_index)
float_arr = arr.astype(float)
print("\nArray converted to float:")
print(float_arr)

6 x 6 Array:
[[61 24 81 70 30 92]
 [96 84 84 97 33 12]
 [31 62 11 97 39 47]
 [11 73 69 30 42 85]
 [67 31 98 58 68 51]
 [69 89 24 71 71 56]]

Sum of each row:
[358 406 287 310 373 380]

Sum of each column:
[335 363 367 423 283 343]

Mean of each row:
[59.67 67.67 47.83 51.67 62.17 63.33]

Maximum value in each row:
[92 97 97 85 98 89]

Column index of maximum value in each row:
[5 3 3 5 2 1]

Array converted to float:
[[61. 24. 81. 70. 30. 92.]
 [96. 84. 84. 97. 33. 12.]
 [31. 62. 11. 97. 39. 47.]
 [11. 73. 69. 30. 42. 85.]
 [67. 31. 98. 58. 68. 51.]
 [69. 89. 24. 71. 71. 56.]]
