In [1]:
import numpy as np
arr = np.arange(1, 21)
arr = arr.reshape(4, 5)
print("Reshaped Array:")
print(arr)
sub_array = arr[1:3, 2:5]
print("\nExtracted Sub-array:")
print(sub_array)
variance = np.var(sub_array)
standard_deviation = np.std(sub_array)
print("\nVariance:")
print(variance)
print("\nStandard Deviation:")
print(standard_deviation)

Reshaped Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Extracted Sub-array:
[[ 8  9 10]
 [13 14 15]]

Variance:
6.916666666666667

Standard Deviation:
2.6299556396765835
