In [12]:
import numpy as np
np.random.seed(10)
arr = np.random.randint(1, 100, size=(10, 10))
print("Original 10 x 10 Array:")
print(arr)
A = arr[0:5, 0:7]
B = arr[0:7, 0:5]
C = arr[5:10, 0:7]
print("\nArray A (5 x 7):")
print(A)
print("\nArray B (7 x 5):")
print(B)
print("\nArray C (5 x 7):")
print(C)
sum_AC = A + C
print("\nSum of A and C:")
print(sum_AC)
multiply_AB = np.dot(A, B)
print("\nMultiplication of A and B:")
print(multiply_AB)

Original 10 x 10 Array:
[[10 16 65 29 90 94 30  9 74  1]
 [41 37 17 12 55 89 63 34 73 79]
 [50 52 55 78 70 14 26 14 93 87]
 [31 31 90 13 66 32 58 37 28 19]
 [94 78 23 24 95 12 29 75 89 10]
 [16 19 81 72 89 12 18 47  8 76]
 [29 34 85 97 89 45  6  5 72 89]
 [89 51 55 35 16 78 89 16  7 86]
 [23 12 13 93 97 63 58 80 43 58]
 [98 51 46 41 90 74 38  1 19 24]]

Array A (5 x 7):
[[10 16 65 29 90 94 30]
 [41 37 17 12 55 89 63]
 [50 52 55 78 70 14 26]
 [31 31 90 13 66 32 58]
 [94 78 23 24 95 12 29]]

Array B (7 x 5):
[[10 16 65 29 90]
 [41 37 17 12 55]
 [50 52 55 78 70]
 [31 31 90 13 66]
 [94 78 23 24 95]
 [16 19 81 72 89]
 [29 34 85 97 89]]

Array C (5 x 7):
[[16 19 81 72 89 12 18]
 [29 34 85 97 89 45  6]
 [89 51 55 35 16 78 89]
 [23 12 13 93 97 63 58]
 [98 51 46 41 90 74 38]]

Sum of A and C:
[[ 26  35 146 101 179 106  48]
 [ 70  71 102 109 144 134  69]
 [139 103 110 113  86  92 115]
 [ 54  43 103 106 163  95 116]
 [192 129  69  65 185  86  67]]

Multiplication of A and B:
[[15739 14857 19341 1