In [1]:
import numpy as np
np.random.seed(20)
arr = np.random.randint(1, 100, (10, 10))
print("Original 10 x 10 Array:")
print(arr)
print("\n2D Arrays:")
print("\n1 x 100:")
print(arr.reshape(1, 100))
print("\n2 x 50:")
print(arr.reshape(2, 50))
print("\n4 x 25:")
print(arr.reshape(4, 25))
print("\n5 x 20:")
print(arr.reshape(5, 20))
print("\n10 x 10:")
print(arr.reshape(10, 10))
print("\n20 x 5:")
print(arr.reshape(20, 5))
print("\n25 x 4:")
print(arr.reshape(25, 4))
print("\n50 x 2:")
print(arr.reshape(50, 2))
print("\n100 x 1:")
print(arr.reshape(100, 1))
print("\n3D Arrays:")
print("\n1 x 1 x 100:")
print(arr.reshape(1, 1, 100))
print("\n1 x 2 x 50:")
print(arr.reshape(1, 2, 50))
print("\n1 x 4 x 25:")
print(arr.reshape(1, 4, 25))
print("\n1 x 5 x 20:")
print(arr.reshape(1, 5, 20))
print("\n2 x 5 x 10:")
print(arr.reshape(2, 5, 10))
print("\n2 x 10 x 5:")
print(arr.reshape(2, 10, 5))
print("\n4 x 5 x 5:")
print(arr.reshape(4, 5, 5))
print("\n5 x 5 x 4:")
print(arr.reshape(5, 5, 4))
print("\n5 x 10 x 2:")
print(arr.reshape(5, 10, 2))
print("\n10 x 5 x 2:")
print(arr.reshape(10, 5, 2))

Original 10 x 10 Array:
[[91 16 96 29 91 10 21 76 23 72]
 [35 97 41 86 91 27 84 17 63 17]
 [ 8 99  7 27 14 76 59 26  4 75]
 [76 62 78 84 58 95 33 11  7 76]
 [19  4 78 18 44 17 19 80 91 60]
 [72 76 30 46  7 64 79 25 19 94]
 [34 79 43 95  4 19 71 53 23 15]
 [ 5 28 76  9  7 27 80 83 79 11]
 [34 86 18 41 83 43 61 85 31 37]
 [ 9 49 20 49 96 54 11 39 10 61]]

2D Arrays:

1 x 100:
[[91 16 96 29 91 10 21 76 23 72 35 97 41 86 91 27 84 17 63 17  8 99  7 27
  14 76 59 26  4 75 76 62 78 84 58 95 33 11  7 76 19  4 78 18 44 17 19 80
  91 60 72 76 30 46  7 64 79 25 19 94 34 79 43 95  4 19 71 53 23 15  5 28
  76  9  7 27 80 83 79 11 34 86 18 41 83 43 61 85 31 37  9 49 20 49 96 54
  11 39 10 61]]

2 x 50:
[[91 16 96 29 91 10 21 76 23 72 35 97 41 86 91 27 84 17 63 17  8 99  7 27
  14 76 59 26  4 75 76 62 78 84 58 95 33 11  7 76 19  4 78 18 44 17 19 80
  91 60]
 [72 76 30 46  7 64 79 25 19 94 34 79 43 95  4 19 71 53 23 15  5 28 76  9
   7 27 80 83 79 11 34 86 18 41 83 43 61 85 31 37  9 49 20 49 96 54 11 